[tools]
ghq = "latest"
python = "3.11"
zellij = "latest"
node="24"
chezmoi = "2.68.1"
fzf = "latest"
zoxide = "latest"
lazygit = "latest"
deno = "latest"

[settings]
override_tool_versions_filenames = ["none"]
